sudo: required
language: cpp
services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1404
        - BUILD_TYPE=standard
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604
        - BUILD_TYPE=standard
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1804
        - BUILD_TYPE=standard
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1804
        - BUILD_TYPE=cmake
    - os: linux
      env:
        - DOCKER_IMAGE=centos7
        - BUILD_TYPE=standard
    - os: linux
      env:
        - DOCKER_IMAGE=fedora29
        - BUILD_TYPE=standard
    - os: linux
      env:
        - DOCKER_IMAGE=fedora29
        - BUILD_TYPE=cmake
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1611
        - BUILD_TYPE=standard
        - EXTRA_PARAMS="dpdk /dpdk-stable-16.11.9"
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1711
        - BUILD_TYPE=standard
        - EXTRA_PARAMS="dpdk /dpdk-stable-17.11.6"
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1811
        - BUILD_TYPE=standard
        - EXTRA_PARAMS="dpdk /dpdk-stable-18.11.1"
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1811
        - BUILD_TYPE=cmake
        - EXTRA_PARAMS="dpdk /dpdk-stable-18.11.1"
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1902
        - BUILD_TYPE=standard
        - EXTRA_PARAMS="dpdk /dpdk-19.02"
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1902
        - BUILD_TYPE=cmake
        - EXTRA_PARAMS="dpdk /dpdk-19.02"
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-pfring
        - BUILD_TYPE=standard
        - EXTRA_PARAMS="pf_ring /PF_RING"
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-pfring
        - BUILD_TYPE=cmake
        - EXTRA_PARAMS="pf_ring /PF_RING"
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: BUILD_TYPE=cmake
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode9
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode9.1
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode9.2
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode9.3
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode10
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode10.1
      env: BUILD_TYPE=standard
    - os: osx
      compiler: clang
      osx_image: xcode10.1
      env: BUILD_TYPE=cmake


before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ci/configure-${BUILD_TYPE}.sh ${TRAVIS_OS_NAME}; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v $(pwd):/PcapPlusPlus -w /PcapPlusPlus -it seladb/${DOCKER_IMAGE} ci/configure-${BUILD_TYPE}.sh ${TRAVIS_OS_NAME} ${EXTRA_PARAMS}; fi
  
script:
  - ERR_CODE=0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ci/build-and-test-${BUILD_TYPE}.sh || ERR_CODE=$?; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v $(pwd):/PcapPlusPlus -w /PcapPlusPlus -it seladb/${DOCKER_IMAGE} ci/build-and-test-${BUILD_TYPE}.sh || ERR_CODE=$?; fi
  - (exit $ERR_CODE)

